spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: a-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/a-service/**
              filters:
                - RewritePath=/api/a-service/(?<segment>.*), /api/${segment}
            - id: b-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/b-service/**
              filters:
                - RewritePath=/api/b-service/(?<segment>.*), /api/${segment}
            - id: c-service
              uri: http://localhost:8084
              predicates:
                  - Path=/api/c-service/**
              filters:
                - RewritePath=/api/c-service/(?<segment>.*), /api/${segment}